import Head from "next/head";
import Header from "./header";
import Footer from "./footer";
import SSRProvider from "react-bootstrap/SSRProvider";

export default function Layout({ children }) {
    return (
        <>
            <SSRProvider>
                <Head>
                    <title>Game Master's Companion</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className="bg-dark d-flex flex-column min-vh-100">
                    <Header />

                    <div className="bg-dark px-4 py-1 my-1 text-center flex-grow-1">
                        {children}
                    </div>
                    <Footer />
                </main>
            </SSRProvider>
        </>
    );
}
